### ISSUE TITLE
Help building for aarch64

### ISSUE THREAD

**Issue by renesecur** [CardanoSolutions/ogmios#189]
I'd like to build Ogmios for ARM64. I've come a long way, but seem to be stuck. This issue is an ask for help to see if we can get it working.

Please find a Dockerfile attached that I am using. Note that I've copied parts (GCH, Cabal and Libsodium) from the Dockerfile I have been using already to successfully build cardano-node. The tricky bit I think is with stack.

I've found https://github.com/commercialhaskell/stack/issues/2103#issuecomment-972329065 this comment. It mentions that they are looking to add aarch64 build artifacts to their releases and I can see one for 2.7.1 which I am grabbing in my Dockerfile.

The part where it seems to be failing is with the actual stack command. I have no idea whether it is a compatibility between stack and cabal/GHC versions or that ogmios requires higher than 2.7.1 of stack.

This is the build error I'm currently running into:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/89156350/158803122-3681102a-f2af-4b0d-a2a7-58c0288d8d45.png">

[Dockerfile.txt](https://github.com/CardanoSolutions/ogmios/files/8284427/Dockerfile.txt)
 
 Btw: git clone command [here](https://ogmios.dev/getting-started/building/#-server) can be improved to use the https link as the git link requires authentication

**Comment by KtorZ** [comment]
@renesecur, a little disclaimer: I am very not versed in system architecture and this is really touching the edge of my expertise :/ 

My get-go approach here would be to look at Haskell.nix and the cross-compilation features from it. Regarding your approach however, note that there's no reason to use `stack` here; Ogmios does also support cabal builds; I do mostly use stack for development because I find it more developer-friendly, but the cabal builds are supported and maintained (since they're used as part of the current nix pipeline). 

Thus, if you're already familiar with cabal and got something to work for cardano-node, I'd encourage you to continue in that direction?

**Comment by renesecur** [comment]
Excellent. That was the golden tip. Got it building now at least. Next step is to test the binary actually does what it's supposed to.

Updated Dockerfile attached. Ran for 59 minutes on AWS CodeBuild with config
```
        Type: ARM_CONTAINER
        Image: "aws/codebuild/amazonlinux2-aarch64-standard:2.0"
        ComputeType: BUILD_GENERAL1_LARGE

```
[Dockerfile.txt](https://github.com/CardanoSolutions/ogmios/files/8287486/Dockerfile.txt)

**Comment by KtorZ** [comment]
@renesecur that's nice! Are you going to maintain this configuration somewhere versioned? Maybe we can link to it from the user guide?

**Comment by rene84** [comment]
Yes I will, but we have all our code in codeCommit at the moment. I'll move this one to github for ease of use

**Comment by KtorZ** [comment]
@renesecur May we close this one in the end :thinking:  ?
