### ISSUE TITLE
Vasil hardfork compatibility

### ISSUE THREAD

**Issue by ngua** [CardanoSolutions/ogmios#215]
Apologies if I've missed something, but I wanted to ask if there is an existing plan to upgrade Ogmios for compatibility with features introduced after the Vasil hardfork. I couldn't find any issues or milestones referencing this

We use Ogmios extensively and will start Vasil testnet testing fairly soon. We would be happy to try to upstream any changes we need to make to Ogmios if there's no existing upgrade plan

Thank you for creating Ogmios!

**Comment by KtorZ** [comment]
Thanks for reaching out, and know that all I am waiting for is a release of `cardano-node`. Given the timeline that was shared by Input Output recently, I expect this to be anytime soon. I am reluctant to upgrade dependencies before that because it is currently a moving a target and it often leads to double-work to upgrade and re-upgrade as things move around. 

There's however in practice very little visibility as for when the next cardano-node will be released; The upgrade should take between 1 and 3 days from the moment cardano-node is released with support for Vasil. 

(side-note: mind sharing what you're using Ogmios for :no_mouth:? I am always curious to heard use-cases and how people use it.).

**Comment by ngua** [comment]
Thank you for the quick response @KtorZ! I'm very happy to hear that you're planning the upgrade

I completely understand about the dependencies upgrade -- I've done my fair share of Plutus and Cardano dependency bumps, so I know how involved that can be

We use Ogmios in [Plutonomicon/cardano-transaction-lib](https://github.com/Plutonomicon/cardano-transaction-lib/). It's a key component in our runtime. We even made a tool to save datums we get from fetching blocks via Ogmios ([mlabs-haskell/ogmios-datum-cache](https://github.com/mlabs-haskell/ogmios-datum-cache/)). Technically, we use our fork, but the only reason for that is to have deeper Nix integration (we use Nix instead of Stack)
