### ISSUE TITLE
Add address & value to the inputs

### ISSUE THREAD

**Issue by Hathoriel** [CardanoSolutions/ogmios#223]
#### Describe your idea, in simple words.
Add address and value fields to the inputs

Right now we have this interface in the Cardano Ogmios [chain sync client ](https://ogmios.dev/typescript-client/chain-sync/) 
```
export interface TxIn {
    txId: TxId;
    index: number;
}

```

I would like to add the address and value:
```
export interface TxIn {
    txId: TxId;
    index: number;
    address: string;
    value: number;
}

```
I don't insist on these exact types, but you know my point.

#### Why is it a good idea?
I need more information about transactions. Right now I don't have these values and if I need to get these details I need to connect to the GraphQL interface, which adds an unnecessary dependency to the system.
#### Are you willing to work on it yourself?
If it were a simple change I would do it.

**Comment by KtorZ** [comment]
Hi there!

This is generally not possible because of the nature of how the UTxO graph is constructed. Ogmios itself doesn't not store any data; it derives everything from the cardano-node itself and merely provide a more friendly interface to low-level interfaces offered by the node. The node itself also does not maintain historical data on UTxO. Indeed, as transaction outputs are consumed, they are removed from the UTxO set. 

Therefore, it isn't generally possible to _resolve_ the address and value corresponding to _any_ transaction input; and certainly not on historical data. If you're using the chain-sync protocol then it is likely that you would want your application to also keep track of the past seen outputs to allow performing a lookup later on. 

Having said that, know that you can query any UTxO by TxIn via the [state-query protocol](https://ogmios.dev/api/#operation-publish-/?Local-State-Query) though, this only works for UTxO (that is, previous outputs that haven't been spent yet). 

If you need to access historical data, then you will need to query a chain-index; either by constructing the index yourself, or by using some existing tool / service that does this. For example: [kupo](https://github.com/CardanoSolutions/kupo) or [scrolls](https://github.com/txpipe/scrolls) are likely what you're looking for.
