### ISSUE TITLE
ogmios-node for mainnet network

### ISSUE THREAD

**Issue by NanuIjaz** [CardanoSolutions/ogmios#323]
Hi, ktorz, cardanosolutions/cardano-node-ogmios:latest is not working when deployed to AWS via cdk. However preprod works fine. and when i deployed this image  cardanosolutions/cardano-node-ogmios:v5.6.0_1.35.7-mainnet , i am getting below. Kindly check and let me know which mainnet stable version i can use. 

<img width="485" alt="image" src="https://github.com/CardanoSolutions/ogmios/assets/122975171/55047255-8876-4295-b694-9ce72127d435">

**Comment by KtorZ** [comment]
Latest is indeed undergoing a massive rework which will be finalized in the upcoming days. In particular. The dashboard is lagging a bit behind and hasn't been updated yet. 

If you stick to 5.6.0 though, there should be no problem. What you see on your screenshot is simply the node syncing. Ledger state queries are only available from the Shelley era onwards, so that means your node is likely still in the Byron era. You need to let it synchronise with the network.

**Comment by NanuIjaz** [comment]
Thank you now i can see epoch. How about the network it still shows "unknown" ?

**Comment by NanuIjaz** [comment]
I see the network as well. Thanks for the reply.
