### ISSUE TITLE
Docker image tags without network name

### ISSUE THREAD

**Issue by GrzegorzDrozda** [CardanoSolutions/ogmios#326]
### What Git revision / release tag are you using?

v6.0.0

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

Docker images tags without cardano network name.

### What should be the expected behavior?

Docker images tagged:
```
v6.0.0-mainnet
v6.0.0-previewv
v6.0.0-preprod
```

### If applicable, what are the logs from the server around the occurence of the problem?

n/a

**Comment by KtorZ** [comment]
Hello, this is expected and has indeed changed with v6.0.0. 

The network tag was slightly misleading for the Ogmios image because there's nothing network-specific about image / executable beside the configuration files that were bundled with it. 

So now, the image ships with configuration files for all networks (under /config/$NETWORK)
