### ISSUE TITLE
Block Data retrun wrong output asset data

### ISSUE THREAD

**Issue by zhp1254** [CardanoSolutions/ogmios#327]
### What Git revision / release tag are you using?

v5.6.0

### Do you use any client SDK? If yes, which one?

None

### Describe what the problem is?

get wrong asset output by nextBlock method
wrong tx：https://cardanoscan.io/transaction/9a6433bf5b74e52b65528a37979eedd16479d04c2935ff6621cddd87e4db461f?tab=utxo

the 9a6433bf5b74e52b65528a37979eedd16479d04c2935ff6621cddd87e4db461f in cardanoscan transfer one asset
but nextBlock return 20th asset in vout

step 
{"jsonrpc":"2.0","method":"findIntersection","params":{"points":[{"slot":99084296,"hash":"95d870ba843ea0bcd63c05f1f37385dad08b89c009e2232f0391e39cdb191a14"}]},"id":{"request_id":"df5XzoWh8i4AcEaU"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}
{"jsonrpc":"2.0","method":"nextBlock","id":{"request_id":"kI79uFnwAxAE7ckg"}}

then get block:9092146 data & tx 
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/f6d090bc-e5cd-4056-a62c-0cd499ed7e48)

### What should be the expected behavior?

ada version
cardano-node 1.35.7 - linux-x86_64 - ghc-8.10
git rev 0000000000000000000000000000000000000000

start cmd：
docker run -itd   --name cardano-node-ogmios   -p 1337:1337   -v /data/cardano-ogmios/db:/db   cardanosolutions/cardano-node-ogmios:latest

### If applicable, what are the logs from the server around the occurence of the problem?

no error log

**Comment by zhp1254** [comment]
http://127.0.0.1:1337 not ok
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/90be44dc-f1a1-484d-8f16-87cd11606629)

**Comment by KtorZ** [comment]
I am not sure why you would assume a bug in Ogmios here and not in CardanoScan? 

Which may also be a slightly wrong conclusion. It is very much possible that CardanoScan only shows tokens that have registered metadata. So that output could be filled with unknown tokens that are simply not shown in the UI. 

Ogmios gets its data directly from the node so I hardly think there's anything wrong. And if there is, it is unlikely to be with Ogmios. 

Also, the json-rpc API has been introduced in v6.0.0; yet the json format shown on your screenshot is the one from v5.6.0. So I am not sure what version you're using exactly but it's neither v5.6.0 nor v6.0.0 but likely some kind of intermediate unreleased version. Not that it would matter regarding your main discrepancy but it would certainly explain the dashboard errors.

**Comment by zhp1254** [comment]
fixed by send slow

**Comment by KtorZ** [comment]
I have no idea what you mean by that. I'd love to understand whether there was a problem or not. Perhaps it is necessary to notify CardanoScan's maintainers of an issue?

**Comment by zhp1254** [comment]
> 

![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/7efe7a31-e5f7-49a7-8895-d0842ff7efd8)
v5.6.0

**Comment by zhp1254** [comment]
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/02072084-e057-4699-9b67-4047748a1444)
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/49021894-31a4-4c51-a12a-04edbd3e34ab)
and "queryLedgerState/utxo" api not found , bug "queryLedgerState/protocolParameters" api work

**Comment by zhp1254** [comment]
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/3f74df3e-e03a-4215-a5d2-92e4921a83c2)
![image](https://github.com/CardanoSolutions/ogmios/assets/18046237/d0a554fa-c75c-47f9-b9fd-f76b450a8ef7)
and "queryLedgerState/utxo" api not work
