### ISSUE TITLE
Support Compact Serialization in TS client

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#51]
https://ogmios.dev/mini-protocols/local-chain-sync/#compact-serialization

**Comment by KtorZ** [comment]
Note: I haven't found a good way to document / specify the absent fields in the JSON-schema. I didn't want to resort to marking them as optional, and I don't really want to down the path of maintaining two spec files for each mode. Possibly, the "compact" one _could be_ generated from the first one with some mask overlay to limit the cost of it. 

Or maybe three's some fancy operator in the latest JSON-schema spec which could help (currently using draft 7 but there has been an actual first version published recently). 

While am I saying all that? Because I think it'll end up causing issue with the TypeScript client's types.

**Comment by KtorZ** [comment]
Closing until further re-assessment.
