### ISSUE TITLE
clients/TypeScript - Handling large integers

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#95]
#### What Git revision are you using? 
`4e2ae0e7b421193cfd4ef4a4a326227c04c61e48`
#### What operating system are you using, and which version?
N/A

#### Describe what the problem is? 
The current implementation uses the internal JSON parser, which will round large integers and loose precision.

#### What should be the expected behavior?
Handle the known issue by parsing numbers to either a string, making it possible to manipulate the value using [bignumber.js](https://www.npmjs.com/package/bignumber.js), native [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), or offer both with a configurable interface. I'm leaning towards `BigInt` exclusively as I think we can justify [most modern browsers](https://caniuse.com/bigint) support the primitive, and supporting both will be very awkward and introduces nasty complexity in the client interfaces.

We will need to either fork [json-schema-to-typescript](https://www.npmjs.com/search?q=json-schema-to-typescript) or rewrite the `number` type to `bigint` secondarily, as surprisingly [this issue has never been raised](https://github.com/bcherny/json-schema-to-typescript/search?q=bigint), so there doesn't appear to be any way to configure this.

```TypeScript
import JSONBig from 'json-bigint'

JSONBig({ alwaysParseAsBig: true, useNativeBigInt: true }).parse(message)
  ```

**Comment by rhyslbw** [comment]
@KtorZ thoughts?

**Comment by KtorZ** [comment]
I've never been fond of representing number as strings, unless this is abstracted away and not visible from an application standpoint. BigInt looks like the way to go. 

Note that, while some numbers may overflow in the API, it's only a fraction of them. For example, Lovelace values may not overflow as the total Ada supply is bounded and well below the MAX_SAFE_INTEGER. Thus, I guess it could be handled on a case-by-case, possibly adding some special flag in the JSON specification (while the problem is relevant to JavaScript / TypeScript, it may also be relevant for other implementation languages (e.g. PHP). 

Forking json-schema-to-typescript could be good, if we intend to also submit the changes upstream (maintaining a fork isn't ideal). I think this could be nicely handled using the `maximum` validation property on JSON schema, using `BigInt` "by default" (though this may break existing implementation, so properly better turned on via some options) unless there's an explicit safe upper-bound.
